// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_word_master_iv = "CgkImYHm3eQDEAIQFA"; // <GPGSID>
        public const string leaderboard_the_challengers = "CgkImYHm3eQDEAIQBQ"; // <GPGSID>
        public const string achievement_word_master_i = "CgkImYHm3eQDEAIQBg"; // <GPGSID>
        public const string achievement_the_explorer = "CgkImYHm3eQDEAIQCw"; // <GPGSID>
        public const string achievement_the_expert_ii = "CgkImYHm3eQDEAIQGQ"; // <GPGSID>
        public const string achievement_the_challenger_ii = "CgkImYHm3eQDEAIQDQ"; // <GPGSID>
        public const string achievement_the_expert_iii = "CgkImYHm3eQDEAIQGg"; // <GPGSID>
        public const string achievement_word_master_v = "CgkImYHm3eQDEAIQCQ"; // <GPGSID>
        public const string achievement_lots_of_letters = "CgkImYHm3eQDEAIQHg"; // <GPGSID>
        public const string achievement_the_stylist = "CgkImYHm3eQDEAIQCg"; // <GPGSID>
        public const string achievement_lucky_guess_iii = "CgkImYHm3eQDEAIQFQ"; // <GPGSID>
        public const string achievement_the_expert_v = "CgkImYHm3eQDEAIQHA"; // <GPGSID>
        public const string achievement_lucky_click = "CgkImYHm3eQDEAIQEQ"; // <GPGSID>
        public const string achievement_the_challenger_iii = "CgkImYHm3eQDEAIQDg"; // <GPGSID>
        public const string achievement_the_expert_iv = "CgkImYHm3eQDEAIQGw"; // <GPGSID>
        public const string achievement_the_challenger_v = "CgkImYHm3eQDEAIQEA"; // <GPGSID>
        public const string achievement_the_challenger_iv = "CgkImYHm3eQDEAIQDw"; // <GPGSID>
        public const string achievement_the_expert_i = "CgkImYHm3eQDEAIQGA"; // <GPGSID>
        public const string achievement_lucky_guess_iv = "CgkImYHm3eQDEAIQFg"; // <GPGSID>
        public const string leaderboard_limit_breakers = "CgkImYHm3eQDEAIQHw"; // <GPGSID>
        public const string achievement_the_challenger_i = "CgkImYHm3eQDEAIQDA"; // <GPGSID>
        public const string achievement_lucky_guess_i = "CgkImYHm3eQDEAIQEg"; // <GPGSID>
        public const string achievement_word_master_ii = "CgkImYHm3eQDEAIQBw"; // <GPGSID>
        public const string achievement_word_master_iii = "CgkImYHm3eQDEAIQCA"; // <GPGSID>
        public const string achievement_lucky_guess_v = "CgkImYHm3eQDEAIQFw"; // <GPGSID>
        public const string achievement_100 = "CgkImYHm3eQDEAIQHQ"; // <GPGSID>
        public const string achievement_lucky_guess_ii = "CgkImYHm3eQDEAIQEw"; // <GPGSID>

}

